import Head from 'next/head';
import Hello from '../components/hello';

import Intro from '../components/intro';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* intro */}
      <Intro/>
      <Hello/>

      {/* skills */}

      {/* about */}

      {/* projects */}

      {/* contact */}
    </div>
  )
}
